print("          TOKO Mainan 17")
print("        ******************")
print("Masukkan Nama Pembeli : Ilham Bintang")
print("Masukkan Kode Mainan : AVENGERS-0101")
print("Masukkan Harga : 100000")
print("Masukkan Jumlah Beli : 9")
print("=======================================")
print("Nama Pembeli = Ilham Bintang")
print("Kode Mainan  = AVENGERS-0101")
hrg = (100000)
print("Harga        = 100000")
jml = (9)
print("Jumlah Beli  = 9")
total = (hrg * jml)
print("Total        = " + str(total))
